spring.application.name=Hethong_QuanlyDetai

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/student_topic_management?serverTimezone=Asia/Ho_Chi_Minh&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
logging.level.org.hibernate=OFF
logging.level.org.springframework=OFF